#!/bin/bash
# USAGE
# e2t [seconds] 
# e2t -i [yyyy-mm-dd hh:mm:ss]

if [ "$1" = "-i" ];then
	if [ -z $3  ];then
		comm=$(echo $0 | awk -F"/" '{print $NF}')
		echo "a> (date) to (seconds) : $comm [seconds]"
		echo "b> (seconds) to (date) : $comm -i [yyyy-mm-dd hh:mm:ss.sss]"
	else
		time=$2" "$3
		sec=$(date -d "$time UTC" +%s)
		msec=$(date -d "$time UTC" +%N | cut -c 1-3)
		bmsec=$(date -d "$time UTC" +%N | cut -c 4-9)
		msec=$(echo $msec.$bmsec | awk '{printf "%03.0f\n",$1}')
		echo $sec.$msec
	fi
else
	if [ -z $2  ];then
		comm=$(echo $0 | awk -F"/" '{print $NF}'i)
		echo "a> (date) to (seconds) : $comm [seconds]"
		echo "b> (seconds) to (date) : $comm -i [yyyy-mm-dd hh:mm:ss.sss]"
	else
	sec=$(echo $1 | awk -F. '{print $1}')
		msec=$(echo $1 | awk -F. '{print $2}' | cut -c 1-3)
		bmsec=$(echo $1 | awk -F. '{print $2}' | cut -c 4-9)
		msec=$(echo $msec.$bmsec | awk '{printf "%03.0f\n",$1}')
		sec=$(echo $sec | awk '{printf "%.0f\n", $1-32400}')
		date -d @"$sec" +%Y"-"%m"-"%d" "%H":"%M":"%S".$msec"
	fi
fi
