#!/bin/bash
input=$1
if [ $1 ];then
	existence=$(ls $input | wc -l)
	if [ "$existence" != "0" ];then
		evinfo=$(cat $input | awk '{if($1=="YEAR" && $2=="MO" && $3=="DA") nr=NR+1; if(NR==nr) print $0}')
		if [ "$evinfo" ];then
			evtime=$(echo "$evinfo" | cut -c 1-24)
			evla=$(echo "$evinfo" | cut -c 25-34 | awk '{print $1,$2}' | awk -F"[ ]" '{printf "%.4f", $1+$2/60}')			
			evlo=$(echo "$evinfo" | cut -c 35-45 | awk '{print $1,$2}' | awk -F"[E]" '{printf "%.4f", $1+$2/60}')
			evdp=$(echo "$evinfo" | cut -c 46-200 | awk '{print $1}')
			rms=$(echo "$evinfo" | cut -c 46-200 | awk '{print $2}')
			errH=$(echo "$evinfo" | cut -c 46-200 | awk '{print $3}')
			errZ=$(echo "$evinfo" | cut -c 46-200 | awk '{print $4}')

#			echo $evtime $evla $evlo $evdp $rms $errH $errZ

			y=$(echo "$evtime" | awk '{print $1}' | awk -F"-" '{print $1}')
			m=$(echo "$evtime" | awk '{print $1}' | awk -F"-" '{print $2}')
			d=$(echo "$evtime" | awk '{print $1}' | awk -F"-" '{print $3}')
			H=$(echo $evtime | cut -c 12-13)
			M=$(echo $evtime | cut -c 14-15)
			S=$(echo $evtime | cut -c 16-21 | awk '{print $1}')
			Osec_min=$(htoe $y $m $d $t $H $M 00.00)
			Osec=$(echo $Osec_min $S | awk '{printf "%.5f", $1+$2}')
			O=$(etoh $Osec)

			y=$(echo $O | awk '{printf "%4d", $1}')
			m=$(echo $O | awk '{printf "%02d", $2}')
			d=$(echo $O | awk '{printf "%02d", $3}')
			j=$(date -d "$y/$m/$d" +%j)
			H=$(echo $O | awk '{printf "%02d", $4}')
			M=$(echo $O | awk '{printf "%02d", $5}')
			S=$(echo $O | awk '{printf "%.3f", $6}' | awk -F. '{printf "%s\n", $1}'| awk '{printf "%02d",$1}')
			MS=$(echo $O | awk '{printf "%.3f", $6}' | awk -F. '{printf "%s\n", $2}' | awk '{printf "%03d",$1}')

			echo -n $y $m $d "("$j")" $t $H $M $S"."$MS " "
			echo $evla $evlo $evdp $rms $errH $errZ | awk '{printf "%7.4f %8.4f %7.2f %6.2f %6.2f %6.2f\n",$1,$2,$3,$4,$5,$6}'
		else
			echo "NoResult:  $input"
		fi
	else
		echo "NoSuchFile:  $input"
	fi
else
	comm=$(echo $0 | awk -F"/" '{printf "%s",$NF}')
	echo "USAGE: $comm [hypinv result fname (.prt)]"
fi
