#!/bin/bash
if [ -z $2 ];then
com=$(echo $0 | awk -F"/" '{print $NF}')
cat <<catend
USAGE: $com [input filename] [output filename]

== input file structure ==
yyyy-mm-dd hh:mm:ss.s
stnm1 stla1 stlo1 Parr1 Sarr1 (any comments)
stnm2 stla2 stlo2 Parr2 Sarr2 (any comments)
stnm3 stla3 stlo3 Parr3 Sarr3 (any comments)
...

*1st line: reference time.
Parr, Sarr: seconds w.r.t. reference time.
*If there is no P or S, put "x".
*To comment specific line, add "#".
catend
exit 0
fi

input=$1
HYPphase=$2;echo -n > $HYPphase
### MAKING HYPOINVERSE PHASE FILE ###
IFS=$'\n'
	
odate=$(head -n 1 $input | awk '{print $1}')
otime=$(head -n 1 $input | awk '{print $2}')
y=$(echo $odate | awk -F"-" '{print $1}')
m=$(echo $odate | awk -F"-" '{print $2}')
d=$(echo $odate | awk -F"-" '{print $3}')
H=$(echo $otime | awk -F":" '{print $1}')
M=$(echo $otime | awk -F":" '{print $2}')
S=$(echo $otime | awk -F":" '{print $3}')

for line in $(cat $input | grep -v '#' | grep -v ":");do
	stnm=$(echo $line | awk '{printf "%-4s", $1}')
	stla=$(echo $line | awk '{printf "%s", $2}')
	stlo=$(echo $line | awk '{printf "%s", $3}')
	Parr=$(echo $line | awk '{printf "%s", $4}')
	Sarr=$(echo $line | awk '{printf "%s", $5}')

	origintime=$(htoe $y $m $d $H $M $S)

	Parrtime=$(echo $origintime | awk -v Parr=$Parr '{printf "%.3f", $1+Parr}')
	Parrtime=$(etoh $Parrtime | awk '{printf "%s%02d%02d%02d%02d%06.3f",substr($1,3,4),$2,$3,$4,$5,$6}')

	Sarrtime=$(echo $origintime | awk -v Sarr=$Sarr '{printf "%.3f", $1+Sarr}')
	Sarrtime=$(etoh $Sarrtime | awk '{printf "%s%02d%02d%02d%02d%05.2f",substr($1,3,4),$2,$3,$4,$5,$6}')
	Sdatetime=$(echo $Sarrtime | cut -c 1-10)
	Ssec=$(echo $Sarrtime | cut -c 11-15)

#	datetime=$(date -d "$odate $otime + $Sarr second" +%y%m%d%H%M)
#	sec=$(date -d "$odate $otime + $Sarr second" +%S)
#	msec=$(date -d "$odate $otime +  $Sarr second" +%N | awk '{printf "%02.0f", $1/10000000}')
#	Sdatetime=$datetime
#	Ssec=$sec.$msec

	if [ "$Parr" != "x" ];then
		echo $stnm $Parrtime | awk '{printf "%-4sIP 0 %s\n",$1,$2}'>> $HYPphase
	fi
	if [ "$Sarr" != "x" ];then
		echo $stnm $Sdatetime $Ssec | awk '{printf "%-4s     %s            %sIS\n",$1,$2,$3}' >> $HYPphase
	fi
done
echo "Making phasefile [$HYPphase] done!" 1>&2
